import { MD3LightTheme, type MD3Theme } from 'react-native-paper';

export const materialTheme: MD3Theme = {
  ...MD3LightTheme,
  roundness: 3,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#176B5B',
    onPrimary: '#FFFFFF',
    primaryContainer: '#A7F2DE',
    onPrimaryContainer: '#002019',
    secondary: '#4E635C',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#D0E8DF',
    onSecondaryContainer: '#0A1F19',
    tertiary: '#806A00',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#FFDF72',
    onTertiaryContainer: '#261A00',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#410002',
    background: '#FBFDF9',
    onBackground: '#191C1A',
    surface: '#FBFDF9',
    onSurface: '#191C1A',
    surfaceVariant: '#DDE5E0',
    onSurfaceVariant: '#414944',
    outline: '#717973',
    outlineVariant: '#C1C9C4',
    inverseSurface: '#2E312F',
    inverseOnSurface: '#EFF1ED',
    inversePrimary: '#8CD5C2',
  },
};
